# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = true

format = """
$username$hostname$directory
$character
"""

right_format = """\
$cmd_duration
"""


# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[ğŸ­§ğŸ­’](fg:blue)[ âœ ](bg:blue fg:#000000)[î‚°](fg:blue)"
error_symbol = "[ğŸ­§ğŸ­’](fg:red)[ âœ— ](bg:red fg:#000000)[î‚°](fg:red)"


[username]
style_user = "bg:blue fg:#000000"
style_root = "red bold"
format = "[ğŸ­ƒ](fg:blue)[$user ]($style)"
disabled = false
show_always = true


[hostname]
ssh_only = false
format =  "[î‚¼ ](bg:cyan fg:blue)[$hostname ](bg:cyan fg:#000000)[î‚¼ ](fg:cyan bg:green)"
trim_at = ".companyname.com"
disabled = false


[directory]
home_symbol = "ï€• "
read_only = " ï€£ "

truncate_to_repo = true
truncation_length = 4
truncation_symbol = "./"

style = "bg:green fg:black"
format = '[$path ]($style)[ğŸ­](fg:green)'


[directory.substitutions]
"/" = " î‚± "
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "


[cmd_duration]
min_time = 0
format = '[ğŸ¬ˆğŸ¬–ğŸ¬¥ğŸ¬… ](bg:yellow fg:#000000)[took $duration](bg:yellow fg:#000000)[ ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—](bg:yellow fg:#000000)'


# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

